// Generated by CoffeeScript 1.12.1
(function() {
  var casper, class_name, class_time, delaytime, end_time, end_time_str, loopcnt, maxloop, moment, now, password, scan_time, sleep_time, test_flag, user, util;

  casper = require("casper").create({
    verbose: true,
    logLevel: 'error',
    waitTimeout: 120000,
    pageSettings: {
      userAgent: 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'
    }
  });

  util = require("utils");

  moment = require('moment');

  if (casper.cli.has('test-flag')) {
    test_flag = true;
  }

  maxloop = 1200;

  loopcnt = 0;

  delaytime = 1000;

  user = casper.cli.raw.get("user");

  password = casper.cli.raw.get('password');

  class_time = casper.cli.raw.get("class-time");

  class_name = casper.cli.raw.get("class-name");

  scan_time = "21:59:00";

  casper.echo(scan_time + " " + delaytime + " " + user + ":" + password + " " + class_time + " " + class_name, "INFO");

  casper.Waiter = function() {
    var i, id, idtext, index, j, k, len, len1, r, row, rows, s, selector, t, td;
    if (!this.exists('tr.virginRowStyle, tr.virginAltRowStyle')) {
      this.wait(delaytime, function() {
        this.echo((moment().format('HH:mm:ss')) + " " + (loopcnt++) + ": Wait 1s", "INFO");
        if (test_flag != null) {
          this.click('#phContentTop_lbDate_7');
          return this.waitForSelector('#phContentTop_lbDate_7.dateActive');
        } else {
          this.click('#phContentTop_lbDate_8');
          return this.waitForSelector('#phContentTop_lbDate_8.dateActive');
        }
      });
    } else {
      this.echo((moment().format('HH:mm:ss')) + " Open", "INFO");
      selector = 'tr.virginRowStyle, tr.virginAltRowStyle';
      rows = this.getElementsInfo(selector);
      this.echo((moment().format('HH:mm:ss')) + " After getElement " + rows.length, 'INFO');
      for (i = j = 0, len = rows.length; j < len; i = ++j) {
        row = rows[i];
        td = row.html.match(/<td[^>]*>\s*([^<]*)/g);
        t = [];
        for (index = k = 0, len1 = td.length; k < len1; index = ++k) {
          r = td[index];
          s = r.match(/<td[^>]*>\s*([^<]*)/);
          t.push(s[1]);
        }
        idtext = row.html.match(/classdetail\.aspx\?id\=([^\"]*)/);
        if (t[0].toLowerCase() === class_time.toLowerCase() && t[3].toLowerCase().indexOf(class_name.toLowerCase()) >= 0) {
          id = idtext[1];
          break;
        }
      }
      this.echo((moment().format('HH:mm:ss')) + " Click Booking", 'INFO');
      this.click("a[href='classdetail.aspx?id=" + id + "']");
      this.waitForSelector('a#btnNextStep.virginButtonGreen', function() {
        this.echo((moment().format('HH:mm:ss')) + " Click Next Step", 'INFO');
        this.click("a#btnNextStep");
        return this.waitForSelector('a#phContentBottom_btnBookAnother', function() {
          this.echo((moment().format('HH:mm:ss')) + " Finish", 'INFO');
          return this.exit();
        });
      });
    }
    return true;
  };

  now = moment();

  end_time_str = (now.format('YYYY-MM-DD')) + " " + scan_time;

  end_time = moment(end_time_str, 'YYYY-MM-DD HH:mm:ss');

  sleep_time = parseInt(end_time.diff(now, 'milliseconds'));

  casper.start("http://mylocker.virginactive.co.th/");

  casper.then(function() {
    this.echo((moment().format('HH:mm:ss')) + " Sleep " + sleep_time, 'INFO');
    if ((test_flag == null) && sleep_time > 0) {
      return this.wait(sleep_time);
    }
  });

  casper.then(function() {
    return this.echo((moment().format('HH:mm:ss')) + " Start", "INFO");
  });

  casper.thenOpen("http://mylocker.virginactive.co.th/www/login.aspx");

  casper.then(function() {
    this.echo((moment().format('HH:mm:ss')) + " Login " + user + ":" + password, 'INFO');
    this.sendKeys('input#phContentBottom_txtMemberID', "" + user);
    this.sendKeys('input#phContentBottom_txtPassword', password);
    this.click('#phContentBottom_btnLogin');
    this.echo((moment().format('HH:mm:ss')) + " Click Login", 'INFO');
    return this.waitForSelector('#phNavBar_MainNavigation1_hlClass');
  });

  casper.then(function() {
    this.click('#phNavBar_MainNavigation1_hlClass');
    this.echo((moment().format('HH:mm:ss')) + " Click Book Class", 'INFO');
    return this.waitForSelector('#bookingSheet');
  });

  casper.then(function() {
    if (test_flag != null) {
      this.click('#phContentTop_lbDate_7');
      this.waitForSelector('#phContentTop_lbDate_7.dateActive');
    } else {
      this.click('#phContentTop_lbDate_8');
      this.waitForSelector('#phContentTop_lbDate_8.dateActive');
    }
    return this.echo((moment().format('HH:mm:ss')) + " Click Last Date", 'INFO');
  });

  casper.then(function() {
    var i, j, ref;
    for (i = j = 0, ref = maxloop; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      this.waitFor(function() {
        return this.Waiter();
      });
    }
    return this.echo('Olayy!', 'INFO');
  });

  casper.run();

}).call(this);
