cp aws-lib.rb ~/Dropbox/booking
cp aws.sh ~/Dropbox/booking
cp azure-lib.rb ~/Dropbox/booking
cp azure.sh ~/Dropbox/booking
cp stopjobs.rb ~/Dropbox/booking
cp startjobs.rb ~/Dropbox/booking
cp startjobs2.rb ~/Dropbox/booking
cp testjobs.rb ~/Dropbox/booking
cp statusjobs.rb ~/Dropbox/booking
cp booking/virgin.js ~/Dropbox/booking
cp booking/virgin-seq.js ~/Dropbox/booking
